// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKNSvkPO-5BKFeYWQ1hVwqVABF0Vo7TE',
    appId: '1:673534642697:android:5153a437270e54cf5546d8',
    messagingSenderId: '673534642697',
    projectId: 'news-f8f11',
    storageBucket: 'news-f8f11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5vrls0uN9q38N3t-A4uLKKEBU40fxwA',
    appId: '1:673534642697:ios:2bc57ab6988970635546d8',
    messagingSenderId: '673534642697',
    projectId: 'news-f8f11',
    storageBucket: 'news-f8f11.appspot.com',
    iosClientId: '673534642697-pdljm17vussq3m6dijh7khd5raiq93ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5TJc-p0NqrZGVQ2aL8H0oMoGsZ7Qzl7k',
    appId: '1:673534642697:web:3e408866f589c9d65546d8',
    messagingSenderId: '673534642697',
    projectId: 'news-f8f11',
    authDomain: 'news-f8f11.firebaseapp.com',
    storageBucket: 'news-f8f11.appspot.com',
  );
}
